### PR TITLE
Skip intersections when max is less than origin

### LINKED ISSUE #20: Intersection testing with bounds below `origin` may include extra intersections
If we have a test case like this:
```rust
#[test]
fn regression3() {
    let mut t = SieveTree::<1, 2, Bounds<1>>::with_granularity(1.);
    let b1 = Bounds {
        min: [10.],
        max: [11.],
    };
    t.insert(b1, b1);

    let intersections = t
        .intersections(Bounds {
            min: [1.],
            max: [2.],
        })
        .map(|(_, bounds)| *bounds)
        .collect::<alloc::vec::Vec<_>>();

    assert_eq!(intersections, []);
}
```

This creates a tree with an origin of 10. When we do intersection testing from world bounds 1..2 though, we convert to tree bounds using that origin. This ends up creating negative `f64`s that are cast to a `u64`, so the tree bounds for intersection become 0..0. The intersection of 0..0 then incorrectly finds an intersection with `b1`.

Technically there should always finer grained intersection testing on the results from `intersections`, but it still seems like we could do something better here. For example, knowing that the max tree bound is outside the tree could allow us to skip intersection testing entirely for this case.

We could also consider shifting the entire tree at the start of `intersections` by calling `ensure_origin_precedes` using the intersections' `min`, so that we can fit the bounds we're trying to test. It might be too weird for `intersections` to take `&mut self` though.

### PR DESCRIPTION
**Pull request by grovesNL**
Fixes #20

- Added a `_checked` variant of `tree_from_world` that will return `None` if the location is before the origin (i.e., can't be represented as a tree location without saturating to 0).
- Use the `_checked` variant to test if the intersection max is less than the origin component-wise, if so early out from the intersection traversal.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1236,4 +1262,24 @@ mod tests {
             }],
         );
     }
+
+    #[test]
+    fn regression3() {
```
Comment (Ralith) [inline src/lib.rs]: Maybe name the test for the property it's checking?

**Review by Ralith — APPROVED** [review]
Thanks!

File: src/lib.rs (hunk 1 above)
Comment (grovesNL) [reply src/lib.rs]: Sure, updated the PR

**Review by Ralith — APPROVED** [review]
